config/routes.rb
Rails.application.routes.draw do
  get "pages/about" , to: "pages#about", as: :about
  # get "product/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "products#index"
  # get "/products", to: "products#index"
  # get "/products/:id", to: "products#show", as: "product"
  resources :products
  resources :customers
  resources :orders
  # get "/customers", to: "customers#index", as: "customer"
  # get "/customer/:id", to: "customer#show", as: "customer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :category, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

    def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_items
  has_many :products, through: :order_items

  validates :customer_id, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :stock_quantity, presence: true, numericality:{only_integer: true, greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
def index
  if params[:customer_query].present?
    @customers = Customer.where("first_name||' '||last_name LIKE ?", "%#{params[:customer_query]}%").order(:last_name)
  else
    @customers = Customer.all.order(:last_name)
  end

  @customers = @customers.page(params[:page]).per(25).order(:last_name) # if using Kaminari
end

  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
    @orders = @orders.page(params[:page]).per(5)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])

    @items = @order.order_items

    @total = @items.sum(:price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all

# apply search filter
@products = @products.where("name LIKE ?", "%#{params[:query]}%") if params[:query].present?

# apply category filter
@products = @products.where(category_id: params[:category_id]) if params[:category_id].present?

# order and paginate
@products = @products.order(:name).page(params[:page]).per(25)


end


  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/customers/index.html.erb
<link rel="stylesheet" href="style.css">


<h1 class="title is-1">Customers</h1>

<%= form_with url: customers_path, method: :get, local: true do %>
  <%= text_field_tag :customer_query, params[:customer_query], placeholder: "Search Customer Name" , class:"input", style:"border: 2px solid grey; width: 300px; margin-left: 113px"%>
  <%= submit_tag "Search", class: "button is-link"%>
  <a class= "button is-primary" style=" " href="/customers/" >Clear Filter</a>

<% end %>



<%# <style>
  table, th, td {
    border: 1px solid black;
    border-collapse: collapse; /* This makes sure borders are not doubled */
  }
  th, td {
    padding: 8px;
  }
</style> %>
<div class="table">
  <table class="table is-striped is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Customer ID</th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id%></td>
          <td><%= link_to customer.full_name, customer_path(customer)%></td>
          <td><%= customer.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>

app/views/customers/show.html.erb
<div class="is-flex  is-align-items-center is-flex-direction-column">
  <div style="margin-top:20px">
  <h1 class="title is-1"><%=@customer.full_name%></h1>

  <div style=" margin-left: 20px">
    <table class="table is-striped is-hoverable is-fullwidth">
      <tr>
        <th>Customer ID</th>
        <td><%=@customer.id%></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%=@customer.email%></td>
      </tr>
    </table>
  </div>

  <h2 class="title is-2">Orders:</h2>
  <div style=" margin-left: 20px">
    <table class="table is-striped is-hoverable is-fullwidth">
      <tr>
        <th>Order ID</th>
        <th>Date</th>
      </tr>
      <% @orders.each do |order| %>
      <tr>
        <td> <%= link_to order.id, order_path(order) %></td>
        <td> <%=order.order_date%>
      </tr>
      <% end %>

    </table>
  </div>
      <div class="pagination is-centered" role="navigation" aria-label="pagination">
      <%= paginate @orders%>
    </div>
  <br>
  <a class= "button is-link" style="margin-left:250px;" href="/customers" >Go back</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=5,IE=9" ><![endif]-->
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<%= render "shared/header"%>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<h1 class="title is-1">Order ID: <%=@order.id%></h1>

<p class="title is-3">Order date: <%=@order.order_date%></p>



<div class="table">
  <table class="table is-striped is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Product ID</th>
        <th>Title</th>
        <th class="has-text-centered">Unit Price</th>
        <th class="has-text-centered">Quantity</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%=item.product.id%></td>
          <td><%= link_to item.product.name, product_path(item.product.id)%></td>
          <td class="has-text-centered"><%= number_to_currency(item.product.price) %></td>
          <td class="has-text-centered"><%= item.quantity %></td>
          <td><%= number_to_currency(item.price) %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<h2 class="has-text-right" style="margin-right:250px; font-weight: bold; font-size: 25px">Total: <%= number_to_currency(@total) %></h2>
<br>
<a class= "button is-link is-pulled-right" style="margin-right:250px;" href="/customers/<%=@order.customer.id%>" >Go back</a>

app/views/products/index.html.erb
<link rel="stylesheet" href="style.css">

<h1 class="title is-1">Products</h1>


  <div class="table">
    <table id="products" class="table is-striped is-hoverable is-fullwidth">
      <thead>
        <tr >
          <th>Product ID</th>
          <th>Name</th>
          <th>Description</th>
          <th class="has-text-centered">Price</th>
          <th class="has-text-centered">Stock Quantity</th>
          <th >Category</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%=product.id%></td>
            <td><%= link_to product.name, product_path(product)%></td>

            <%unless product.description.blank?%>
            <td><%= product.description %></td>
            <%else%>
            <td>No Description</td>
            <%end%>

            <td class="has-text-centered"><%= number_to_currency(product.price) %></td>
            <td class="has-text-centered"><%= product.stock_quantity %></td>
            <td><%= product.category.category%></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination is-centered" role="navigation" aria-label="pagination">
      <%= paginate @products%>
    </div>
  </div>

app/views/products/show.html.erb
<h1 class="title is-1"><%= @product.name %></h1>

  <div style="width: 520px; margin-left: 20px">
    <table class="table is-striped is-hoverable is-fullwidth">
      <tr>
        <th>Description</th>
            <%unless @product.description.blank?%>
            <td><%= @product.description %></td>
            <%else%>
            <td>No Description</td>
            <%end%>
      </tr>

      <tr>
        <th>Price</th>
        <td><%= number_to_currency(@product.price) %></td>
      </tr>
      <tr>
        <th>Stock Quantity</th>
        <td><%= @product.stock_quantity %></td>
      </tr>
      <tr>
        <th>Category</th>
        <td><%= @product.category.category %></td>
      </tr>
    </table>
  </div>
  <br>
<%= link_to "Go back", :back, class: "button is-link", style:"margin-left:450px;" %>

app/views/shared/_header.html.erb
<nav class="navbar is-link" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Joezer", root_path, class: "navbar-item" , style: "color: white; font-weight: bold; font-size: 30px"%>
      <%= link_to "About", about_path, class: "navbar-item" %>
      <%= link_to "Customers", customers_path, class: "navbar-item" %>
      <%= link_to "Products", products_path, class: "navbar-item" %>
    </div>

    <!-- Hamburger menu for mobile -->
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarMenu" class="navbar-end" style="margin-top:10px; margin-right: 10px;">

    <%= form_with url: products_path, class: "control", method: :get, local: true do %>
      <%= text_field_tag :query, params[:query], class:"input", placeholder: "Search Product Names", style:"width: 300px; height: 37px" %>

      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :category, params[:category_id]), include_blank: "All Categories", class:"dropdown-content" %>
      <%= submit_tag "Filter" , class: "button is-primary" , style:"height: 37px; margin-right:5px;"%>

    <a class= "button is-primary is-pulled-right" style="height: 37px; " href="/products/" >Clear Filter</a>

    <% end %>
  </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const burgers = Array.from(document.querySelectorAll('.navbar-burger'));
    burgers.forEach(burger => {
      burger.addEventListener('click', () => {
        const target = document.getElementById(burger.dataset.target);
        burger.classList.toggle('is-active');
        target.classList.toggle('is-active');
      });
    });
  });
</script>